app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api:
    resource: "@AppBundle/Resources/config/api_routing.yml"


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
